spring:
  application:
    name: idAuthentication
  datasource:
    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202303-06;encrypt=true;trustServerCertificate=true;
    username: CS544-202303-06
    password: 491d2748-7cf1-4585-813c-be592cdf1b4c
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
logging:
  file:
    path: .
    name: /Logging/${spring.application.name}/log
#server:
#  port: 56061
